[package]
name = "vecdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.7.0"
serde = "1.0.167"
serde_json = "1.0.100"
serde_derive = "1.0.167"